apple/pkl-lsp

- src/main/kotlin/org/pkl/lsp/Builder.kt
- src/main/kotlin/org/pkl/lsp/PklTextDocumentService.kt
- src/main/kotlin/org/pkl/lsp/VirtualFile.kt
- src/main/kotlin/org/pkl/lsp/ast/PklModuleUri.kt
- src/main/kotlin/org/pkl/lsp/ast/PklNodeFactory.kt
- src/test/kotlin/org/pkl/lsp/LSPTestBase.kt
`java.io.File` is a legacy API; it's better to use `java.nio.file.Path` whenever possible.
This doesn't change `JarFile` because that one isn't used and perhaps should be removed (`Path` can represent files inside a jar).
This is built on top of https://github.com/apple/pkl-lsp/pull/5 and https://github.com/apple/pkl-lsp/pull/6. Only the last commit should be reviewed.
> Switch files to NIO API

- src/main/kotlin/org/pkl/lsp/ClientCapabilities.kt
- src/main/kotlin/org/pkl/lsp/LSPUtil.kt
- src/main/kotlin/org/pkl/lsp/PklClientOptions.kt
- src/main/kotlin/org/pkl/lsp/PklLSPServer.kt
- src/main/kotlin/org/pkl/lsp/Project.kt
- src/main/kotlin/org/pkl/lsp/ast/Extensions.kt
- src/main/kotlin/org/pkl/lsp/features/GoToDefinitionFeature.kt
- src/main/kotlin/org/pkl/lsp/features/HoverFeature.kt
- src/main/kotlin/org/pkl/lsp/services/PklProjectManager.kt
- src/main/kotlin/org/pkl/lsp/services/SettingsManager.kt
- src/main/resources/org/pkl/lsp/errorMessages.properties
This defines initialization options that clients can send during the initialize request,
to configure the behavior of the server.
This also introduces extended capabilities that clients can notify the server about.
Also:
* Switch some messages from `sendActionableNotification` to `showMessageRequest`, which is a built-in message.
* Look for Pkl CLI on $PATH if not configured by client.
* Render doc comments as normal URIs instead of `command:pkl.open.file`, unless configured to do so.
> Make LSP configurable using initialization options

- src/main/kotlin/org/pkl/lsp/VirtualFile.kt
- src/main/kotlin/org/pkl/lsp/VirtualFileManager.kt
* Unset readError on successful read, and ensure called in synchronized block
* Cache VirtualFiles in a weak map to allow stale files to be garbage collected
> Improve handling of VirtualFile

- src/main/kotlin/org/pkl/lsp/services/PklProjectManager.kt
This fixes an issue where the sync project notification shows up for files that aren't within any workspaces.
> Fix: omit sync notification for files outside workspace

- src/main/kotlin/org/pkl/lsp/VirtualFile.kt
- src/main/kotlin/org/pkl/lsp/ast/ModuleOrClass.kt
- src/main/kotlin/org/pkl/lsp/ast/PklNode.kt
- src/main/kotlin/org/pkl/lsp/util/CachedValuesManager.kt
Currently, all cached values are stored in a global hashmap, which means that these cached values will never get marked for disposal by the garbage collector.
This introduces a `CachedValueDataHolder`, which allows cached values to be written to it. This allows these cached values to be disposed of when the `CacheValueDataHolder` itself is disposed.
> Fix memory leak: improve cache storage granularity

- .circleci/config.pkl
- .circleci/config.yml
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/settings.gradle.kts
- buildSrc/src/main/kotlin/BuildInfo.kt
- buildSrc/src/main/kotlin/ExecutableJar.kt
- gradle.properties
- src/main/kotlin/org/pkl/lsp/LSPUtil.kt
- src/main/kotlin/org/pkl/lsp/Project.kt
- src/main/kotlin/org/pkl/lsp/Release.kt
- src/main/kotlin/org/pkl/lsp/VirtualFile.kt
- src/main/kotlin/org/pkl/lsp/treesitter/NativeLibrary.kt
- src/main/kotlin/org/pkl/lsp/treesitter/PklParser.kt
- src/main/kotlin/org/pkl/lsp/treesitter/TreeSitterPkl.kt
- src/main/kotlin/org/pkl/lsp/util/OS.kt
- src/main/resources/org/pkl/lsp/Release.properties
- src/test/kotlin/org/pkl/lsp/LSPTestBase.kt
- src/test/kotlin/org/pkl/lsp/ParserTest.kt
This implements changes to put native libs in `~/.pkl/editor-support/`. When loading the parser, it first looks for libraries there, and if they don't exist, they get copied from bundled resources.
When building libraries, the os name and architecture get included in the resource path.
This enables starting the jar plainly without needing any extra argument (e.g. no need for CLI flag `-Djava.library.path`, and no need for the `LD_LIBRARY_PATH` env var), and eliminates the need to copy native libraries to the current working dir.
Note: java-tree-sitter doesn't provide any way to provide the library path. To get around this, I'm doing a pretty ugly hack to rewrite the `TreeSitter.java` source file to make it load the tree-sitter library from our custom dir.
> Improve handling of native libraries

- build.gradle.kts
- buildSrc/src/main/kotlin/Architecture.kt
- buildSrc/src/main/kotlin/BuildInfo.kt
- buildSrc/src/main/kotlin/utils.kt
- buildSrc/src/main/kotlin/zig.gradle.kts
- gradle/libs.versions.toml
This uses Zig to compile the native libraries for macOS/linux/windows for the aarch64/amd64 architectures.
This also removes Node.js stuff, which is no longer necessary because we don't use the tree-sitter CLI anymore to build these libraries.
> Use Zig to cross-compile native libs

- src/main/kotlin/org/pkl/lsp/LSPUtil.kt
- src/main/kotlin/org/pkl/lsp/ast/Extensions.kt
- src/main/kotlin/org/pkl/lsp/ast/PklNode.kt
- src/main/kotlin/org/pkl/lsp/ast/TreeSitterNode.kt
- src/main/kotlin/org/pkl/lsp/completion/UnqualifiedAccessCompletionProvider.kt
This will allow unqualified completions when the user didn't type anything:
```pkl
foo = <caret>
foo {
<caret>
}
bar = let (x = <caret>) x
```
> improve completions for unqualified access

- src/main/kotlin/org/pkl/lsp/ast/Expr.kt
- src/main/kotlin/org/pkl/lsp/ast/PklNode.kt
- src/test/kotlin/org/pkl/lsp/ParserTest.kt
While generating the AST for binary expressions we were making wrong assumptions about where the children should be located. This fixes the generation so expressions with comments, errors, or any other kind of node in between will still parse correctly.
> fix binary expressions AST generation

- build.gradle.kts
- gradle/libs.versions.toml
- src/main/kotlin/org/pkl/lsp/PklBaseModule.kt
- src/main/kotlin/org/pkl/lsp/Stdlib.kt
- src/main/kotlin/org/pkl/lsp/VirtualFile.kt
We only need pkl-stdlib; don't need to bring in the entire pkl-core.
> Remove dependency on pkl-core

- .circleci/config.pkl
- .circleci/config.yml
- README.adoc
- build.gradle.kts
* Don't build before publishToSonatype
* Attach workspaces for various publish steps
* Remove `builtBy` marker for publication
* Release notes: don't link to website that doesn't exist
> Touch up publishing

- src/main/kotlin/org/pkl/lsp/documentation/DocCommentMemberLinkProcessor.kt
Handle an edge case where an import might have a name but the import is not resolvable.
> Fix resolve variable in member links

- src/main/kotlin/org/pkl/lsp/LspUtil.kt
- src/main/kotlin/org/pkl/lsp/PklLsp.kt
- src/main/kotlin/org/pkl/lsp/PklLspServer.kt
- src/main/kotlin/org/pkl/lsp/Project.kt
- src/main/kotlin/org/pkl/lsp/analyzers/PklDiagnostic.kt
- src/main/kotlin/org/pkl/lsp/ast/Expr.kt
- src/main/kotlin/org/pkl/lsp/ast/Extensions.kt
- src/main/kotlin/org/pkl/lsp/ast/Member.kt
- src/main/kotlin/org/pkl/lsp/ast/ModuleOrClass.kt
- src/main/kotlin/org/pkl/lsp/ast/PklModuleUri.kt
- src/main/kotlin/org/pkl/lsp/ast/Type.kt
- src/main/kotlin/org/pkl/lsp/cli/LspCommand.kt
- src/main/kotlin/org/pkl/lsp/completion/ModuleUriCompletionProvider.kt
- src/main/kotlin/org/pkl/lsp/completion/StringLiteralTypeCompletionProvider.kt
- src/main/kotlin/org/pkl/lsp/features/CodeActionFeature.kt
- src/test/kotlin/org/pkl/lsp/GoToDefinitionPackagesTest.kt
- src/test/kotlin/org/pkl/lsp/GoToDefinitionTest.kt
- src/test/kotlin/org/pkl/lsp/HoverTest.kt
- src/test/kotlin/org/pkl/lsp/LspTestBase.kt
- src/test/kotlin/org/pkl/lsp/ParserSnippetTestEngine.kt
- src/test/kotlin/org/pkl/lsp/ParserTest.kt
- src/test/kotlin/org/pkl/lsp/SyncProjectsTest.kt
Change capitalization of the following classes:
LSPTestBase -> LspTestBase
LSPUtil -> LspUtil
PklLSP -> PklLsp
PklLSPServer -> PklLspServer
This renaming is consistent with the existing classes LspCommand, PklCli, etc.
> Rename classes for consistency

- build.gradle.kts
- gradle/libs.versions.toml
- src/main/kotlin/org/pkl/lsp/ast/Extensions.kt
- src/main/kotlin/org/pkl/lsp/ast/PklNode.kt
This version fixes two problems where we had to make workarounds:
- `Node.getText()` was not encode-aware.
- `Tree`s were not allowed to be shared between threads.
This PR upgrades the version and removes the workarounds.
> Upgrade to java-tree-sitter 0.24

- build.gradle.kts
- buildSrc/src/main/kotlin/BuildInfo.kt
- fix IntelliJ errors in build.gradle.kts by declaring `buildInfo`
- distinguish between jdkVersion and jdkTargetVersion and set them once in BuildInfo
- it's often preferable to build with the latest JDK version even
if targeting an older version
- enforce jdkTargetVersion in compilation tasks
- prevents accidental use of newer JDK APIs
- run tests with `--enable-native-access=ALL-UNNAMED` to prevent warnings
> Tweak Gradle build

- NOTICE.txt
- build.gradle.kts
This makes spotless update the copyright year when a file is touched.
Also, update NOTICE.txt to include 2025.
> Update copyright year and set up spotless

- src/main/kotlin/org/pkl/lsp/ast/Extensions.kt
Fixes an issue where a typealias might incorrectly be marked as recursive.
> Fix TypeAlias.isRecursive

- src/main/kotlin/org/pkl/lsp/ast/PklNode.kt
- src/main/kotlin/org/pkl/lsp/ast/Terminal.kt
- src/main/kotlin/org/pkl/lsp/ast/TokenType.kt
In tree-sitter, error nodes can possibly have children. However, these nodes aren't very meaningful to analyze, and can possibly cause unexpected exceptions when doing so.
Also: add interpolation start as a token type to be safe.
Closes https://github.com/apple/pkl-lsp/issues/64
> Skip analyzing error nodes

- src/main/kotlin/org/pkl/lsp/type/ComputeDefinitionType.kt
- src/main/kotlin/org/pkl/lsp/type/ComputeExprType.kt
- src/main/kotlin/org/pkl/lsp/util/RecursionManager.kt
- src/test/kotlin/org/pkl/lsp/HoverTest.kt
This prevents stack overflows from occurring when analyzing recursive methods, for example.
Loosely copies `RecursionManager` from the IntelliJ SDK
Closes https://github.com/apple/pkl-lsp/issues/46
> Prevent stack overflow when computing types

- src/main/kotlin/org/pkl/lsp/PklTextDocumentService.kt
- src/main/kotlin/org/pkl/lsp/VirtualFileManager.kt
- src/main/kotlin/org/pkl/lsp/ast/Expr.kt
- src/main/kotlin/org/pkl/lsp/ast/Member.kt
- src/main/kotlin/org/pkl/lsp/ast/ModuleOrClass.kt
- src/main/kotlin/org/pkl/lsp/ast/PklNode.kt
- src/main/kotlin/org/pkl/lsp/ast/Type.kt
- src/main/kotlin/org/pkl/lsp/type/ComputeExprType.kt
- src/main/kotlin/org/pkl/lsp/util/CachedValuesManager.kt
- src/test/kotlin/org/pkl/lsp/ParserTest.kt
This fixes various issues in the LSP
* Fixes parsing of modifier nodes
* Fixes an issue where child nodes are constructed twice (`toNode()`, `toTerminal()` should never be called in the body of a class because they are already initialized when `children` is called)
* Improves child node selection by using field names
* Fixes an issue where stdlib modules can possibly be initialized multiple times
* Fixes possible race conditions to prevent a cached value's provider from being called multiple times
* Treat `PklMethod` as an identifier owner, so that code actions that target them can refer to them by name.
* Cache the result of `computeExprType`
> Miscellaneous fixes

- src/main/kotlin/org/pkl/lsp/Project.kt
- src/main/kotlin/org/pkl/lsp/VirtualFile.kt
- src/main/kotlin/org/pkl/lsp/ast/ModuleOrClass.kt
This fixes an issue where paths in files can possibly resolve to incorrect locations, and sometimes causes infinite recursion.
Note: this fixes an edge case that I don't have a good reproducer for, so this is submitted without a test
> Fix path resolution

- src/main/kotlin/org/pkl/lsp/analyzers/AnnotationAnalyzer.kt
- src/main/kotlin/org/pkl/lsp/analyzers/TypeNameAnalyzer.kt
- src/main/kotlin/org/pkl/lsp/ast/Basic.kt
- src/main/kotlin/org/pkl/lsp/ast/Extensions.kt
- src/main/kotlin/org/pkl/lsp/ast/ModuleOrClass.kt
- src/main/kotlin/org/pkl/lsp/ast/PklNode.kt
- src/main/kotlin/org/pkl/lsp/ast/Type.kt
- src/main/kotlin/org/pkl/lsp/services/DiagnosticsManager.kt
- src/test/files/DiagnosticsSnippetTests/inputs/typename/unresolved.pkl
- src/test/files/DiagnosticsSnippetTests/outputs/typename/unresolved.txt
- src/test/files/ParserSnippetTests/outputs/expr/typeTestAndCast.txt
- src/test/files/ParserSnippetTests/outputs/types/types.txt
This adds diagnostics like "Unresolved reference 'Foo'" when used as a type name.
As part of this, the parse tree is also fixed to better match the IntelliJ parse tree.
> Add analysis for type names

- src/main/kotlin/org/pkl/lsp/ast/Expr.kt
- src/test/files/DiagnosticsSnippetTests/inputs/expr/redundant2.pkl
- src/test/files/DiagnosticsSnippetTests/outputs/expr/redundant2.txt
Fixes an issue where `foo?.bar` is not seen as null propagating
> Fix qualified access analysis

- src/main/kotlin/org/pkl/lsp/actions/PklAddModifierQuickFix.kt
- src/main/kotlin/org/pkl/lsp/actions/PklCodeAction.kt
- src/main/kotlin/org/pkl/lsp/actions/PklSuppressWarningsQuickFix.kt
- src/main/kotlin/org/pkl/lsp/analyzers/ModifierAnalyzer.kt
- src/main/kotlin/org/pkl/lsp/analyzers/PklProblemGroup.kt
- src/main/kotlin/org/pkl/lsp/ast/PklNode.kt
- src/main/kotlin/org/pkl/lsp/ast/Span.kt
- src/test/kotlin/org/pkl/lsp/ModifierQuickfixTest.kt
* Add quickfix to add 'local' modifier
* Add diagnostic for non-local object properties with type annotations
* Misc: Rename: PklSuppressWarningsCodeAction -> PklSuppressWarningsQuickFix
> Improve modifier analysis

- src/main/kotlin/org/pkl/lsp/VirtualFile.kt
- src/main/kotlin/org/pkl/lsp/ast/Member.kt
- src/main/kotlin/org/pkl/lsp/ast/ModuleOrClass.kt
- src/main/kotlin/org/pkl/lsp/ast/PklModuleUri.kt
- src/main/kotlin/org/pkl/lsp/services/DiagnosticsManager.kt
- src/main/kotlin/org/pkl/lsp/services/PackageManager.kt
- src/main/kotlin/org/pkl/lsp/type/ComputeExprType.kt
- src/main/kotlin/org/pkl/lsp/util/CachedValuesManager.kt
This fixes a deadlock that arises when computing diagnostics.
This also generally reduces lock contention (the `getCachedValues()` API now requires a lock to be provided).
> Fix deadlock

- src/main/kotlin/org/pkl/lsp/PklBaseModule.kt
- src/main/kotlin/org/pkl/lsp/analyzers/ExprAnalyzer.kt
- src/main/kotlin/org/pkl/lsp/analyzers/TypeCheckAnalyzer.kt
- src/main/kotlin/org/pkl/lsp/type/Types.kt
- src/test/files/DiagnosticsSnippetTests/inputs/expr/alwaysTrueOrFalse.pkl
- src/test/files/DiagnosticsSnippetTests/outputs/expr/alwaysTrueOrFalse.txt
Because we only check subtype and some constraints relationship, a wrong warning would show
when comparing things to `NonNull`.
```pkl
myOptionalThing: String?
thingsThatAre: Listing<String> = new {
// this was showing: Expression is always true
when(myOptionalThing is NonNull) {
myOptionalThing
}
}
```
Even though this is not idiomatic Pkl (one should use `??` or compare something to `null` directly) we shouldn't show a wrong warning.
> Check for NonNull in diagnostics and type checks
